spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://querybind.cstwej4zhzyv.sa-east-1.rds.amazonaws.com:5432/querybind
    username: querybind
    password: querybind
  liquibase:
    default-schema: public